### ISSUE TITLE
Only Windows?

### ISSUE THREAD

**Issue by SultanSGillani** [pdevito3/craftsman#1]
Is this tool only intended for windows?

I am already getting errors when running the craftsman new:api command. 

`craftsman new:api $HOME/projects/work/template.yaml
Your template file was parsed successfully.
An unhandled exception occured when running the API command.
The error details are: 
The `/home/user/projects/work\Template.Api/Domain\Entities` directory could not be found. `

**Comment by pdevito3** [comment]
Yeah, I hadn't tested this on Linux. Looks like it's rendering the file path in a non Linux friendly format. Will look into this more and put out a patch when I'm able. 

Not ideal, but should still work on windows in the meantime.

**Comment by SultanSGillani** [comment]
I am assuming it would be the same on MacOs since its also Unix Based.

Thanks for the help.

**Comment by pdevito3** [comment]
Okay, there were a couple spots where I was manually dealing with class paths. I updated everything to use `Path.Combine()` and `Path.DirectorySeparatorChar` wherever applicable so it should work across OS's now. 

With that said.. I don't really know of a good way to write a cross OS test for something like this and I only have a windows machine at the moment, so I wasn't able to confirm 100% yet. 

Will plan to spin up a linux instance and try it there at some point to confirm if you're not able, but wanted to give you the chance to work with it ASAP if needed. Will close the ticket for now, but if I missed anything and you run into an issue, let me know and I'll take a look!

**Comment by Jogai** [comment]
Easy to test if you're willing to use something like virtualbox: https://www.osboxes.org/virtualbox-images/
