### ISSUE TITLE
The GetList Feature will not return a list of objects

### ISSUE THREAD

**Issue by amalsharief** [pdevito3/craftsman#105]
When I get the json file from /swagger/v1/swagger.json](https://localhost:7268/swagger/v1/swagger.json)
the GetList will not work as expected as before (Craftsman .17 (OK)) appeared in ver 0.18. Am I doing 
something wrong?
Thanks.

amalsharief. 

The part of swagger.json :

"paths": {
    "/api/organs": {
      "get": {
        "tags": [
          "Organs"
        ],
        "summary": "Gets a list of all Organs.",
        "operationId": "GetOrgans",
        "parameters": [
          {
            "name": "Filters",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "SortOrder",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "PageNumber",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "PageSize",
            "in": "query",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },

**Comment by pdevito3** [comment]
This was by design for the release. I reduced the amount of swagger stuff being generated until I could properly flesh it all out as it's been fairly half baked.
