### ISSUE TITLE
Generated User classes have duplicate identifiers

### ISSUE THREAD

**Issue by NoTuxNoBux** [pdevito3/craftsman#113]
It's a minor bug, but the generated User classes have their own identifier generated whilst they already inherit from `BaseEntity`, which also provides an ID:

```
    [Sieve(CanFilter = true, CanSort = true)]
    public string Identifier { get; private set; }
```

This means there are two GUIDs in the database for each `User`.

Related to this, the generated `PUT` and `POST` calls expect an ID to be passed in the data, which is a bit awkward since `PUT` already expects the ID as parameter and the identifier is usually not a field that clients should be able to update.

### Steps to reproduce

1. Configure authentication through the Wrapt YAML.
2. Generate a new domain based on the YAML file through Wrapt.

### Further technical details

Craftsman version (`dotnet tool list -g`): 0.20.0

**Comment by NoTuxNoBux** [comment]
Hmmm, I just realized that, since Wrapt doesn't generate the actual authentication implementation itself, is this perhaps intended to be the _remote_ identifier on the identity provider rather than the local ID?

**Comment by pdevito3** [comment]
Yeah this is the IDP identifier. Check out how the keycloak portion integrates (ef use policy handler adds a user of non exists) and you'll see. 

Going to close this
