### ISSUE TITLE
Provide a realworld backend

### ISSUE THREAD

**Issue by Jogai** [pdevito3/craftsman#12]
A https://github.com/gothinkster/realworld backend made with craftsman would be valuable because then you can show how far the generation will take you.

**Comment by pdevito3** [comment]
Thanks, good idea! Will try and do this once the tool is more stable. Still building everything out to an initial release.

**Comment by PoisnFang** [comment]
to essentially mimic this then? https://github.com/gothinkster/aspnetcore-realworld-example-app/tree/master/src/Conduit/Infrastructure

**Comment by pdevito3** [comment]
👋 here's a pretty detailed domain driven backend that hopefully gives people a good idea of how you can grow a wrapt app:
https://github.com/pdevito3/PeakLimsApi
