### ISSUE TITLE
Missing using statements in domain entities

### ISSUE THREAD

**Issue by AnNormalie** [pdevito3/craftsman#126]
After scaffolding a new api with craftsman version 0.23.0 I get an error when I try to build the project.
![image](https://github.com/pdevito3/craftsman/assets/86982835/1d1d5246-b759-402a-9188-39d743ce9fc6)

it seems that there are missing using statements in the entities class.
![image](https://github.com/pdevito3/craftsman/assets/86982835/bb96201a-15e6-4163-b468-d51cf78b66ca)
![image](https://github.com/pdevito3/craftsman/assets/86982835/ea19d3fa-a202-4645-80ab-ba54c06b3eed)

Missing usings are:
`using System.ComponentModel.DataAnnotations.Schema;`
`using System.ComponentModel.DataAnnotations;`
`using System.Text.Json.Serialization;` or `using Newtonsoft.Json;`
`using System.Runtime.Serialization;`

### Further technical details

Craftsman version (`dotnet tool list -g`): 0.23.0

**Comment by AnNormalie** [comment]
I just got some time and tried to reproduce it with modifying the example projects, but till now I could not reproduce the bug.
The template file that produces the issue is an older template that have the old relationship mapping, could it be that this produces the issue?

I need to test this tomorrow when I am at work again.

Is the old relation mapping still supported?

**Comment by AnNormalie** [comment]
The Issue with the missing `using System.ComponentModel.DataAnnotations.Schema;` `using System.ComponentModel.DataAnnotations;` statements I got reproduced. When Adding `TableName` and `Schema` to the `Entity Properties` in the yaml/json file. And the `IsRequired` Attribute.

![image](https://github.com/pdevito3/craftsman/assets/86982835/1290d1a8-1d31-4cc4-9942-301896e9c3af)
![image](https://github.com/pdevito3/craftsman/assets/86982835/17f3af78-2ea2-41ca-b28e-8daf924db37b)

**Comment by pdevito3** [comment]
Interesting. Yeah I've actually been trying to move away from attributes to keep things focused on the db config file for the entity and reduce clutter. This one slipped through the cracks. Will try and address in a patch and figure out a longer term plan for after. 

Thanks
