### ISSUE TITLE
GetAll feature doesn't use plural

### ISSUE THREAD

**Issue by AnNormalie** [pdevito3/craftsman#127]
When scaffolding en entity with an `GetAll`-Feature, the feature name doesn't use the plural. Is this intended or a bug?

For example when having an `Orders` Entity with an `GetAll` Feature, I would expect that the Feature would be called `GetAllOrders` instead of `GetAllOrder`
![image](https://github.com/pdevito3/craftsman/assets/86982835/c077573b-426b-4f59-ad79-08a604d9bd43)

### Further technical details

Craftsman version (`dotnet tool list -g`): 0.23.0

**Comment by pdevito3** [comment]
Nice catch thanks. I'll get this in a patch or the next release
