### ISSUE TITLE
Is there an example to use with Azure B2C auth?

### ISSUE THREAD

**Issue by biapar** [pdevito3/craftsman#134]
Is there an example to use with Azure B2C auth?

**Comment by pdevito3** [comment]
No, but you should just be able to do a [standard .NET implementation](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-8.0) with no issues. There's no novelty to the IDP setup in a project that craftsman scaffolds out. 

As far as permissions, you can set up the user policy handler to do whatever makes sense for your use case

**Comment by biapar** [comment]
Ok. I'll try. Thanks.
