### ISSUE TITLE
Is't possible to create a project without entities?

### ISSUE THREAD

**Issue by biapar** [pdevito3/craftsman#135]
Is't possible to create a project without entities?

**Comment by pdevito3** [comment]
Theoretically yes, but i haven't tried? Have you? Whats the use case?

**Comment by biapar** [comment]
I tried but craftman goes in error. I wish only the api .

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Paul DeVito ***@***.***>
Inviato: Wednesday, March 6, 2024 2:09:15 PM
A: pdevito3/craftsman ***@***.***>
Cc: BIAGIO PARUOLO ***@***.***>; Author ***@***.***>
Oggetto: Re: [pdevito3/craftsman] Is't possible to create a project without entities? (Issue #135)


Theoretically yes, but i haven't tried? Have you? Whats the use case?
