### ISSUE TITLE
New project don't create tables under the database

### ISSUE THREAD

**Issue by biapar** [pdevito3/craftsman#136]
I create a small yaml file with one entity. I create the db info sqlserver. 
I boot the project but EF don't execute the migrations.
Why?

**Comment by pdevito3** [comment]
Going to need more info than that to help you

**Comment by biapar** [comment]
I don’t see any error. The program start but no tables.
Where Does Serilog save the log files? No log folder.
Thanks.

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Paul DeVito ***@***.***>
Inviato: Wednesday, March 6, 2024 2:07:38 PM
A: pdevito3/craftsman ***@***.***>
Cc: BIAGIO PARUOLO ***@***.***>; Author ***@***.***>
Oggetto: Re: [pdevito3/craftsman] New project don't create tables under the database (Issue #136)


Going to need more info than that to help you

**Comment by biapar** [comment]
I solved with the command "ef database update" to push data to database🧐

**Comment by pdevito3** [comment]
Serilog just outputs to the console by default. No log folder. 

There is a migrations background service that should be running for you on startup. I need to see your template or project to diagnosis though. No where near enough info to help.

In the meantime, yeah a regular ef command being run manually should work
