### ISSUE TITLE
Case conversion of names is not culture-independent

### ISSUE THREAD

**Issue by scria1000** [pdevito3/craftsman#137]
On machines where the current culture is set to Turkish, case conversion of identifiers result in the letter `I` being lowercased to the [dotless-i](https://en.wikipedia.org/wiki/Dotless_I) (`ı`) variant instead of `i`.

I noticed that the code uses culture-specific `ToLower()`, `ToUpper()` instead of `ToLowerInvariant()`, `ToUpperInvariant()`

Generated docker-compose.yml causes issues with docker compose due to non-English letters not being allowed.

This does not appear to break the tool for now, and it can be remedied with a simple search and replace.

<img src="https://github.com/user-attachments/assets/0e4d1c9f-e5f1-4702-90cd-9b63c88001c8" width="70%">

<details><summary>Generated docker-compose.yaml</summary>
<p>
<img src="https://github.com/user-attachments/assets/68e1100d-63e5-42f5-aadd-a86537f057b8" width="70%">
</p>
</details>

<details><summary>Generated appsettings.json</summary>
<p>
<img src="https://github.com/user-attachments/assets/7ba9ebe7-aabb-489f-9efb-5f327481c9bf" width="70%">
</p>
</details>

### Steps to reproduce

If you are on Windows, install the Language pack for Turkish and set just the Regional format to Turkish.
Or you can just add these lines to the Program.cs of craftsman:

```c#
CultureInfo.DefaultThreadCurrentCulture = CultureInfo.GetCultureInfo("tr-TR");
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.GetCultureInfo("tr-TR");
``` 

Have a ProjectName/ContextName/DatabaseName and/or Entity/Property name that begins with the letter `I` such as Ingredients.

### Further technical details

Craftsman version (`dotnet tool list -g`): 0.26.4

### Similar issues in other projects

https://github.com/CommunityToolkit/dotnet/issues/230

**Comment by pdevito3** [comment]
Appreciate the callout on this! Will try and take a look at it soon

**Comment by pdevito3** [comment]
👋 the newest `v0.27.0` release should resolve this, but I wasn't able to easily test this myself, so I'm going to keep this open for now. Let me know if you're still having issues and I can dig into it some more!
