### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by Christian-Schou** [pdevito3/craftsman#143]
I would love to see workflow support. This would allow for complex workflows tailored for specific features to support business needs more easily. By doing this it would be possible to create everything from a simple task to complex process management within a feature or by publishing events between features or domains.

The ideal solution would be to have the option for creating workflows programmatically or by publishing the Elsa API endpoints for the visual designer to create workflows.

Not sure what would be the best option in terms of publishing the API endpoints, since the endpoints have to be registered within a bounded context.

If possible it would be great to have the option to consume messages in the workflows generated by domain events. This would make it possible to trigger complex workflows when a record is created, updated, deleted, etc...

I hope it makes sense, else please let me know and I will try to come up with a better description of what I see as an initial feature-set. 😃 

Thank you for the great work! 🥳

**Comment by pdevito3** [comment]
I don't see this getting added at the moment but could definitely be a good option for a forked craftsman if you're interested!

**Comment by Christian-Schou** [comment]
Okay, I might make a PR for that. Thank you for considering it 🙂
