### ISSUE TITLE
Hardcoded value (recipies) in  OptionsConfigurationsBuilder.cs

### ISSUE THREAD

**Issue by BuzukBzh** [pdevito3/craftsman#148]
Hi Paul,
Great tool and happy to discover it.
I'm using 0.28.0 (same problem on 0.28.1)
In Craftsman/Builders/OptionsConfigurationsBuilder.cs

https://github.com/pdevito3/craftsman/blob/f3f5ca12b6afa348b807de220abda44c846474e1/Craftsman/Builders/OptionsConfigurationsBuilder.cs#L104

                      .GetSection(RecipeManagementOptions.SectionName)

Should be

                      .GetSection({{className}}.SectionName)

Thx

**Comment by pdevito3** [comment]
fixed! thanks for the callout
