### ISSUE TITLE
Handle relative paths in cli commands

### ISSUE THREAD

**Issue by pdevito3** [pdevito3/craftsman#18]
@JuanCarbo I just started a write up for this and when I went to try it in my CLI (i.e. `craftsman new:api ..\ApiTemplateName.yaml`) and it worked just fine. Could you confirm that it still doesn't work for you?

**Comment by JuanCarbo** [comment]
Just tried it again and it worked. 
![image](https://user-images.githubusercontent.com/18491069/109310147-eb7d2300-7822-11eb-9685-e54fe1f38548.png)

Tried reinstalling the library to see if it had something to do with it being the first run, but still worked.
![image](https://user-images.githubusercontent.com/18491069/109310298-19626780-7823-11eb-8b21-11d97208dbee.png)

Let me know if you think of any other tests I can run.

**Comment by pdevito3** [comment]
No worries, that looks good to me. Going to close this then. Thanks!

**Comment by JuanCarbo** [comment]
Tested it on another computer with a fresh craftsman install. The script got stuck at "Your template has been parsed successfully"

**Comment by pdevito3** [comment]
Can you try closing the windows that you installed from and open another one to try from there? It might have to have a 'fresh start'

**Comment by JuanCarbo** [comment]
Tried from the same window, stuck 
![image](https://user-images.githubusercontent.com/18491069/109374397-d096c700-7893-11eb-9624-41673b8bfbac.png)

Closed powershell, re-opened and works 

![image](https://user-images.githubusercontent.com/18491069/109374441-0fc51800-7894-11eb-981c-65646d1b31a7.png)

Seems to be related with using the same PS instance.

**Comment by pdevito3** [comment]
thanks, this is what i thought. looks like this is [a known sdk issue](https://github.com/dotnet/sdk/issues/8999). will call it out in the docs. thanks!
