### ISSUE TITLE
ContosoUniversity Example

### ISSUE THREAD

**Issue by PoisnFang** [pdevito3/craftsman#25]
I find it a bit difficult to translate what Wrapt is doing when compared to the example repo that Jimmy Bogard made: https://github.com/jbogard/ContosoUniversityDotNetCore-Pages

It would be nice to see your take on the Contoso University example using a WebAPI with Wrapt and eventually adding in a SPA front end as well.

**Comment by Jogai** [comment]
See also #12

**Comment by pdevito3** [comment]
👋 here's a pretty detailed domain driven backend that hopefully gives people a good idea of how you can grow a wrapt app:
https://github.com/pdevito3/PeakLimsApi
