### ISSUE TITLE
Tutorial craftsman new:domain CarbonKitchen.yaml fails on Linux

### ISSUE THREAD

**Issue by mfehlhaber** [pdevito3/craftsman#27]
Creating a template file by copying the one provided in tutorial section "Environment and Swagger Setup", and even placing it in the same directory I run the command `craftsman new:domain`  from leads to the following output:
```
No such file or directory
An unhandled exception occurred when running the API command.
The error details are: 
No such file or directory
```

Nevertheless the following empty directory structure gets created:
```
CarbonKitchen
└── RecipeManagement
    ├── src
    └── tests
```

### Further technical details

Craftsman version (`craftsman version`):
v0.9.3.0

**Comment by pdevito3** [comment]
what version of .net do you have installed? -- `dotnet --version`

**Comment by mfehlhaber** [comment]
`dotnet --version`
5.0.202

**Comment by pdevito3** [comment]
not able to repo, closing
