### ISSUE TITLE
How to return an error when creating a filter with faulty values ?

### ISSUE THREAD

**Issue by BobbyLarone** [pdevito3/craftsman#32]
I've encounterd something very strange.. 
When i'm trying to execute a GET request to retrieve a list of items, i can also specify a filter but when those values are wrong ( ex. guid == leaves) the result still gives me a complete list with all the entities back from the database. ( ex. GetUsers returns all the users)

It looks like there is no validation on the filters. 
How do i return an error when the result of the filter returns nothing?

**Comment by pdevito3** [comment]
Just gave this a shot and it looks like it works fine for non-guids (returns an empty list when no records match the filter), but does indeed not work for guid fields. This is a bug in Sieve. I submitted [a ticket to them](https://github.com/Biarity/Sieve/issues/150). Will try and submit a PR to them myself at some point, but if you want to as well, go for it! 

Closing this as it is not necessarily an issue with craftsman as much as Sieve.
