### ISSUE TITLE
The Name annotation will only be produced for get actions.

### ISSUE THREAD

**Issue by amalsharief** [pdevito3/craftsman#33]
The Name annotation will only be produced for get action  [HttpGet(Name = "GetAddresss")] but not for other actions in the controller. 
Which will produce generic methods for some client generators and errors for the others.

```example csharp
 [HttpGet(Name = "GetAddresss")]     -> Ok
[HttpPost]    without the name property  -> not ok
```

**Comment by pdevito3** [comment]
agreed, all the endpoints should have a name value
