### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by amalsharief** [pdevito3/craftsman#36]
Hi, 
Is there nightly builds available to try some added feature?

Thank you.

Abdoessalam

**Comment by pdevito3** [comment]
No nightly build, but if you want to run craftsman locally you can do this:

1. Clone down the repo
2. Go to ./Craftsman/Craftsman ￼in your terminal
3. Run `dotnet run COMMAND`. For example, `dotnet run add:entity my/entity/file.yaml`

Alternatively you can also run from VS or Rider by adding something like `add:entity my/entity/file.yaml` to your run props.
