### ISSUE TITLE
Update docs on Wrapt

### ISSUE THREAD

**Issue by deepakbaliga** [pdevito3/craftsman#45]
Hi Paul,

Great work on the craftsman project. I'm looking forward to being a hardcore user of wrapt. Spent about a day on the documentation and also looking at the source code. I see a lot of changes that were made in 0.11.x aren't updated on the website. 

Would appreciate it if you could update the documentation. 

Best,
Deepak

**Comment by deepakbaliga** [comment]
Hi @pdevito3 ,

Thanks for getting back to me super quickly. 

There have been a few areas in 0.11.x and I'll try and keep this thread updated with any missing documentation as and when I come across. In fact, even propose to add it if there is a way? 

One of the things that I couldn't find currently is documentation around ForeignKey and other properties surrounding this in Entities documentation. 

If you could add an example as to how to do a nested entity, that would be highly appreciated.
https://wrapt.dev/docs/entities

**Comment by deepakbaliga** [comment]
Or may be even an example in the example repo for 0.11 with Entities and foreign keys

**Comment by pdevito3** [comment]
FK's are something that kind of slip through the cracks. honestly they broke over the course of upgrades and i didn't get a chance to properly address them again until this upcoming release, so i pulled them form the docs for now. 

if you have anything else, feel free to drop it in here or a new docs ticket. rich docs help you all, but also me keep track of it all so i want them to have as much useful content as possible
