### ISSUE TITLE
Tests break in v0.12 when using `DateOnly` or `TimeOnly`

### ISSUE THREAD

**Issue by pdevito3** [pdevito3/craftsman#47]
This isn't a bug in craftsman, but in a library used in wrapt projects. 

Autobogus can not generate fakes on entities using `DateOnly` or `TimeOnly`. This is because Bogus did not support it. They have since released 34.x which provides this support, but autobogus needs to bring it in to their package. You can track the progress of it [here](https://github.com/nickdodd79/AutoBogus/issues/76).

**Comment by sshquack** [comment]
@pdevito3 Thanks for capturing this issue. I ran into this when trying out the .NET 6 features. Perhaps it is in maintenance mode or open to PR contributions. For now, in my scaffolded code, I am planning on replacing Autobogus with Bogus and writing the seeds manually. Long term it would be awesome to have this supported by Autobogus 🤞

**Comment by pdevito3** [comment]
I have a PR into Autobogus that will hopefully be merged in to resolve this.
