### ISSUE TITLE
Getting started does not work on dotnet 6 macOS M1

### ISSUE THREAD

**Issue by sshquack** [pdevito3/craftsman#48]
Thanks for this fantastic project! I'm trying out Craftsman for the first time following https://wrapt.dev/docs/installation The CLI installs successfully but errors out when invoked.

### Steps to reproduce
```
❯ dotnet tool install -g craftsman
You can invoke the tool using the following command: craftsman
Tool 'craftsman' (version '0.12.2') was successfully installed.

❯ craftsman
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' (arm64) was not found.
  - The following frameworks were found:
      6.0.1 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=arm64&rid=osx.12-arm64

❯ echo $?
150

❯ craftsman list
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' (arm64) was not found.
  - The following frameworks were found:
      6.0.1 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=arm64&rid=osx.12-arm64

❯ dotnet tool update -g craftsman
Tool 'craftsman' was reinstalled with the latest stable version (version '0.12.2').
```

### Further technical details

Environment info
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Dependencies are working as expected:
```
❯ dotnet tool list --global
Package Id      Version      Commands
--------------------------------------
craftsman       0.12.2       craftsman
dotnet-ef       6.0.1        dotnet-ef

~/Downloads
❯ dotnet ef --version
Entity Framework Core .NET Command-line Tools
6.0.1

~/Downloads
❯ docker --version
Docker version 20.10.11, build dea9396
```

Dotnet 6 is the only version with native arm64 support for M1 mac. So i do not have dotnet 5 installed.
![Screenshot 000008@2x](https://user-images.githubusercontent.com/5678459/146692298-ab13602a-2e13-45a6-85a1-d90a1457e5da.png)

I created a small web API template with dotnet 6 to verify that it successfully works as expected. How do I get past this error?

**Comment by pdevito3** [comment]
hey @sshquack thanks for reporting this (and for the well written ticket). 

yeah, so this seems to be because Craftsman is still actually using .NET 5 under the hood really just because I didn't have a driver to upgrade yet and wanted to focus on some other stuff, but it would seem I have a good reason now! I'll see if I can get a new release out on .NET 6 for you in the next few days.

Thanks again for letting me know!

**Comment by sshquack** [comment]
@pdevito3 Thank you! I'll watch out for your update and give it another go. Looking forward to trying this out again.

**Comment by pdevito3** [comment]
@sshquack I just published v0.12.3 if you want to give it a whirl! lots of .net 6 updates i want to make but i just bumped the version for now to unblock you. let me know if it doesn't work, otherwise i'll assume it does close this in the next few days :-)

**Comment by sshquack** [comment]
Woot! The new version worked.

```
❯ dotnet tool update -g craftsman
Tool 'craftsman' was successfully updated from version '0.12.2' to version '0.12.3'.

❯ craftsman --version
v0.12.3
```

Thank you for getting this release so fast 🙇  I'm gonna continue reading through the docs.

**Comment by pdevito3** [comment]
Awesome! Feel free to reach out if you have any questions.
