### ISSUE TITLE
Integration tests fails to run sql server on M1 chip

### ISSUE THREAD

**Issue by sshquack** [pdevito3/craftsman#53]
The integration tests fail to run on macOS with M1 because Craftsman relies on [mssql server image](https://hub.docker.com/_/microsoft-mssql-server?tab=reviews) which has not yet been port to ARM64. The current workaround is to use [azure sql edge](https://hub.docker.com/_/microsoft-azure-sql-edge). See [this blog](https://bornsql.ca/blog/you-cant-run-sql-server-on-apple-silicon-and-it-sucks/) for details.

### Steps to reproduce
- Scaffold any default example on macOS with M1 chip
- Try to run integration tests
- Notice that the tests hang-up because the mssql server docker image did not start

### Further technical details

Craftsman version (dotnet tool list -g):

```
❯ dotnet tool list -g
Package Id      Version      Commands
--------------------------------------
craftsman       0.12.3       craftsman
dotnet-ef       6.0.1        dotnet-ef
```

Environment info

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

### Potential solutions

It took a few hours to figure this error. So we could do few things to help anyone else running into this issue:
Option 1: It might be worth to call this out in the getting started docs for folks with M1 chip
Option 2: Detect at Craftsman builder runtime (aka `new:*` commands) that the machine is a macOS with arm64 and generate azure-sql-edge 
Option 3: At test runtime detect that the machine is a macOS with arm64 and use azure-sql-edge image. Can be found using the following:
```
> System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture
Arm64

> System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(OSPlatform.OSX)
true
```

Option 3 seems like a better solution since it would be clear in the code as why azure-sql-edge was chosen over ms-sql-server with some comments. I'd be happy to make a PR if your prefer option 3!

**Comment by pdevito3** [comment]
Oof this doesn't sound fun. Sorry for the headache here. 

Do you know if MS has talked about a timeline for porting it to ARM64? Did you get yours working with ASE? Would be curious to see what it looks like and if there needs to be updates to areas other than the db utility (e.g. checkpoint and helper methods come to mind).

I do agree that option 3 would be best, but i am a little worried about the overhead it would add to the project.

At the very least, I can definitely update the docs and maybe even point to a gist with updates, but I could be open to option 3 to make it more portable. Could you send me what the end result might look like for the db util with option 3 and let me know if you had to update checkpoint, the helpers, or anything else I might be forgetting?
