### ISSUE TITLE
Allow ID fields to be Byte, Int16, 32 or 64 instead of Guid

### ISSUE THREAD

**Issue by danarrib** [pdevito3/craftsman#57]
First I must say that Wrapt is a FANTASTIC work. Super useful. Congratulations.

But I noticed that all "Id" fields generated by it are Guid type, which translates to a UNIQUEIDENTIFIER datatype in SQL Server.

This datatype takes 16 bytes per row, which grows really fast on tables with lots of records.

It would be great if we can specify the data type of the Id field... Default can still be Guid, but it would be nice to have the option to choose between Byte (TinyInt), Int16 (SmallInt), Int32 (Int) or Int64 (BigInt). Some tables has a very predictable number of rows and it would be nice to save some bytes by allocating only the necessary amount of space to that field.

Greetings from Brazil 🇧🇷

**Comment by pdevito3** [comment]
hey @danarrib, thanks for the note.

I would love to be able to support this, but it would add way too much overhead and complexity to the project at this point. I have some ideas to potentially support this in the future, but there will be some larger shifts needed to make that happen. 

For now, if you want to do this, the project will support it with some pretty minor changes. You should just have to update your base entity when creating a new boundary and likely have some minor tweaks to tests on entity scaffolding. should still be a big net timesaver overall.
