### ISSUE TITLE
Missing dependencies on  craftsman new example

### ISSUE THREAD

**Issue by mrs01dev** [pdevito3/craftsman#73]
craftsman new example 
create solution with Missing dependencies  , that is related to RabbitMQ  Bus.

![image](https://user-images.githubusercontent.com/64358630/164114423-4bb1c14b-9ef1-4ee8-84a6-63b39a46c4f9.png)

### Steps to reproduce
 dotnet tool install -g craftsman
 craftsman new:example

What steps can we follow to reproduce the issue?
 craftsman new:example

### Further technical details

craftsman           0.14.0       craftsman

**Comment by pdevito3** [comment]
Hey, thanks for the heads up. Which example was it?

**Comment by pdevito3** [comment]
hey, just got a chance to look at this. it's from a last minute change i made before the release for a dependency i missed. updating now and will have a new package out tonight!
