### ISSUE TITLE
Postgres Json data type Support

### ISSUE THREAD

**Issue by pratikpparikh** [pdevito3/craftsman#78]
For entities is there a support for JSON?  What would be the best way to approach a JSON data type for Postgres vs other supported database types?

**Comment by pdevito3** [comment]
this is more of an ef question i think. https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco

the scaffolding doesn't support it directly, but you can still create the string prop and add the attribute and such as needed
