### ISSUE TITLE
Running Locally

### ISSUE THREAD

**Issue by zsyphon** [pdevito3/craftsman#79]
Hi again,

I'm looking at creating a branch and adding to the project. I've been trying to run the source locally with visual studio code. However, none of my "new domain dm.yml" arguments are run. Can you recommend a way to run and debug the program locally?

**Comment by pdevito3** [comment]
hey, yeah sorry i haven't had enough interest to invest in a `Contributing.md`

you can run it by cd'ing to craftsman and running `dotnet run new example` for instance (note there's no colon anymore in the develop branch for the upcoming release

**Comment by pdevito3** [comment]
If you're doing a fork to make your own version then go right ahead, but if you're looking to add a feature to this project let's chat first so you don't waste time

**Comment by pdevito3** [comment]
btw @zsyphon I pushed some small updates for bugs last night on a couple commands you might want to get from upstream if you forked it

**Comment by zsyphon** [comment]
Awesome thank you! We will be making PRs in the future too.

**Comment by pdevito3** [comment]
Sweet! Feel free to ping me with any questions.

I want to clean up the craftsman codebase more to make forks super easy to manage for people who want to make it their own, but hopefully it's still manageable for now 🙂
