### ISSUE TITLE
Project IntegrationTests  - class TestFixture   -Error	CS0103

### ISSUE THREAD

**Issue by mrs01dev** [pdevito3/craftsman#95]
build solution  for craftsman new domain  ,produce Error	CS0103

### Steps to reproduce

1-   craftsman new domain  ****
2- build solution 
Result:
building project  " ****.IntegrationTests.csproj" -- FAILED.
Error	CS0103	The name 'SetupDateAssertions' does not exist in the current context	 *****.IntegrationTests	
TestFixture.cs	69
-->

### Further technical details

Craftsman version (`dotnet tool list -g`):
craftsman           0.16.5       craftsman
dotnet-ef           6.0.8        dotnet-ef

**Comment by pdevito3** [comment]
can you share the template file you're using? I'm not able to repro

**Comment by pdevito3** [comment]
nvm, seems to be a sqlserver thing. will get this in the next patch. Thanks!
