### ISSUE TITLE
Craftsman Tutorial - BFF giving two 404s on page load

### ISSUE THREAD

**Issue by CLFPosthumus** [pdevito3/craftsman#99]
When following the tutorial, the React app gets two 404s on page load.
`GET https://localhost:4378/@id/D:/src/custom.css net::ERR_ABORTED 404 (Not Found)`
`https://localhost:4378/@id/D:/src/components/Notifications net::ERR_ABORTED 404 (Not Found)`

----
### Steps to reproduce

1. Run docker-compose commands for the backend
2. Create new project following tutorial
3. Add ShoppingListEntity 
4. Add BFF using the command
5. Run `npm i` in the root folder
6. Page will not load due to 404s

----

Package Id           Version         Commands
cake.tool            2.2.0           dotnet-cake
craftsman            0.16.6          craftsman
dotnet-counters      6.0.257301      dotnet-counters
dotnet-dump          6.0.257301      dotnet-dump
dotnet-ef            6.0.1           dotnet-ef`

**Comment by pdevito3** [comment]
👋 thanks for the heads up. One thought is that you're using `npm` when the project is setup to use `yarn`. Might be worth a try? 

Regardless, I'm going to close this as I'm moving the project towards [a Next JS template](https://github.com/pdevito3/next-template-wrapt-sand) to avoid some of the problems of .NET clashing with JS land. Feel free to check it out if you want. It's still early so has some things I'd like to cleanup and fix, but might be a good alternative for you.
